### ISSUE TITLE
Framerange missmatch

### ISSUE THREAD

**Issue by timsergeeff** [ynput/ayon-resolve#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When i crate publisheble clip and publish it it publishes with error whith was mentioned here (https://github.com/ynput/ayon-resolve/issues/5) but in integrates anyway BUT with wrong frame range: one frame less than nedeed so further publishing for example from nuke isnt working because of a out of frame range error

### Expected Behavior:

Correct frame range

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1) take any video file (my test was mov apple prores 25fps)
2)put it inside timeline
3) thim it to 10 frames, create publisheble shot with 10 frames handles
4) get an error
5) see that it has been published anyway
6) see published shot is 29 frames long but in AYON datadasae it is 30

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Additional context:

resolve 19

and i have the same thing happening in hiero but without integration error, just one frame shorter than in ayon database
(https://github.com/ynput/ayon-hiero/issues/2)

**Comment by BigRoy** [comment]
I gave this a quick go.

---

My project at 25 FPS:

1. Loaded a H264 clip of six frames.
2. Created publishable clip instance, published.
3. The loader showed:

![image](https://github.com/ynput/ayon-resolve/assets/2439881/a8a52f26-83a6-426e-9db2-a11770a67451)

So it shows 6 frames long in the database and also loads fine with the original length. Seems ok?
Are you sure you Resolve project and timeline are also set to 25 FPS?
Could you maybe provide a brief demo file that failed for you?

**Comment by timsergeeff** [comment]
This happens with prores files 

https://cloud.blankpig.com/s/yL9iJBc4PazFJYK
Try it

**Comment by timsergeeff** [comment]
this problem is ffmpeg purely, mp4 works fine, prores looses 1 frame at the endm, mxf from arri not rendering at all

prepublish conversion to exr aces cg solves issue and makes sence aas further work will be rendered in exr anyway

**Comment by jakubjezek001** [comment]
Here is reaction on Hiero issue https://github.com/ynput/ayon-hiero/issues/2#issuecomment-2396750279 - this also applies to this issue.
